GET http://localhost:8080/api/game
Accept: application/json

###
POST http://localhost:8080/api/developer
Content-Type: application/json
Accept: application/json

{
  "name": "Blizzard"
}

###
POST http://localhost:8080/api/game
Content-Type: application/json
Accept: application/json

{
  "name": "WoW",
  "genres": [
    "MMO",
    "RPG"
  ],
  "developer": {
    "id": 1,
    "name": "Blizzard"
  },
  "publishers": [
    {
      "name": "Activision"
    }
  ]
}

###
GET http://localhost:8080/api/publisher?name=Some
Authorization: Basic YWRtaW5AdnNhLnNrOjE= # admin@vsa.sk:1
Accept: application/json

###
POST http://localhost:8080/api/publisher
Content-Type: application/json
Accept: application/json

{
  "name": "Microsoft",
  "games": []
}
